name: 'C++ CI'

on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg integrate install

      - name: Install Boost.Test
        run: ./vcpkg/vcpkg install boost-test:x64-windows

      - name: Configure CMake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" -DPATCH_VERSION=${{ github.run_number }}

      - name: Build project
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build --build-config Release

      - name: Package project
        run: cmake --build build --target package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: build/*.zip
